=== engagepoint/labs-questionnaire-wizard/wizard-ejb/src/main/resources/XSDforWizard.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="questionnaire-forms">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="questionnaire-form" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="form-name" />
                            <xs:element name="pages">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="page" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="page-number"/>
                                                    <xs:element name="groups-of-questions">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="group" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element type="xs:string" name="group-name" />
                                                                            <xs:element name="questions">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="question" maxOccurs="unbounded">
                                                                                            <xs:complexType>
                                                                                                <xs:sequence>
                                                                                                    <xs:element type="xs:string" name="question-title"/>
                                                                                                    <xs:element type="xs:string" name="question-type"/>
                                                                                                    <xs:element type="xs:string" name="help-text"/>
                                                                                                    <xs:element name="dependent-questions">
                                                                                                        <xs:complexType>
                                                                                                            <xs:sequence>
                                                                                                                <xs:element name="dependent-question" maxOccurs="unbounded">
                                                                                                                    <xs:complexType>
                                                                                                                        <xs:sequence>
                                                                                                                            <xs:element type="xs:string" name="question-id"/>
                                                                                                                            <xs:element type="xs:string" name="required-answer"/>
                                                                                                                        </xs:sequence>
                                                                                                                    </xs:complexType>
                                                                                                                </xs:element>
                                                                                                            </xs:sequence>
                                                                                                        </xs:complexType>
                                                                                                    </xs:element>
                                                                                                    <xs:element name="multiple-choice-options">
                                                                                                        <xs:complexType>
                                                                                                            <xs:sequence>
                                                                                                                <xs:element type="xs:string" name="option" maxOccurs="unbounded"/>
                                                                                                            </xs:sequence>
                                                                                                        </xs:complexType>
                                                                                                    </xs:element>
                                                                                                    <xs:element name="checkboxes-options">
                                                                                                        <xs:complexType>
                                                                                                            <xs:sequence>
                                                                                                                <xs:element type="xs:string" name="option" maxOccurs="unbounded"/>
                                                                                                            </xs:sequence>
                                                                                                        </xs:complexType>
                                                                                                    </xs:element>
                                                                                                    <xs:element name="choose-from-list-options">
                                                                                                        <xs:complexType>
                                                                                                            <xs:sequence>
                                                                                                                <xs:element type="xs:string" name="option" maxOccurs="unbounded"/>
                                                                                                            </xs:sequence>
                                                                                                        </xs:complexType>
                                                                                                    </xs:element>
                                                                                                    <xs:element name="range">
                                                                                                        <xs:complexType>
                                                                                                            <xs:simpleContent>
                                                                                                                <xs:extension base="xs:string">
                                                                                                                    <xs:attribute type="xs:int" name="range-begin"/>
                                                                                                                    <xs:attribute type="xs:int" name="range-end"/>
                                                                                                                </xs:extension>
                                                                                                            </xs:simpleContent>
                                                                                                        </xs:complexType>
                                                                                                    </xs:element>
                                                                                                    <xs:element name="grid">
                                                                                                        <xs:complexType>
                                                                                                            <xs:sequence>
                                                                                                                <xs:element name="columns">
                                                                                                                    <xs:complexType>
                                                                                                                        <xs:sequence>
                                                                                                                            <xs:element type="xs:string" name="column" maxOccurs="unbounded"/>
                                                                                                                        </xs:sequence>
                                                                                                                    </xs:complexType>
                                                                                                                </xs:element>
                                                                                                                <xs:element name="rows">
                                                                                                                    <xs:complexType>
                                                                                                                        <xs:sequence>
                                                                                                                            <xs:element type="xs:string" name="row" maxOccurs="unbounded"/>
                                                                                                                        </xs:sequence>
                                                                                                                    </xs:complexType>
                                                                                                                </xs:element>
                                                                                                            </xs:sequence>
                                                                                                        </xs:complexType>
                                                                                                    </xs:element>
                                                                                                </xs:sequence>
                                                                                                <xs:attribute type="xs:string" name="answer-required"/>
                                                                                                <xs:attribute type="xs:int" name="question-id"/>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== engagepoint/labs-questionnaire-wizard/wizard-ejb/src/main/resources/XMLforWizard2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<questionnaire-forms
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='XSDforWizard.xsd'>
    <questionnaire-form>
        <form-name>Test 2, Second Generated XML file</form-name>
        <pages>
            <page page-number="10">
                <groups-of-questions>
                    <group>
                        <group-name></group-name>
                        <questions>
                            <question answer-required="true" question-id="2">
                                <question-title></question-title>
                                <question-type>RANGE</question-type>
                                <help-text></help-text>
                                <dependent-questions>
                                </dependent-questions>
                                <options>
                                    <option></option>
                                </options>
                                <range range-begin="32" range-end="12"/>
                                <grid>
                                    <columns>
                                    </columns>
                                    <rows>
                                    </rows>
                                </grid>
                            </question>
                        </questions>
                    </group>
                </groups-of-questions>
            </page>
        </pages>
    </questionnaire-form>

</questionnaire-forms>

=== engagepoint/labs-questionnaire-wizard/wizard-ejb/src/main/resources/prevTestTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<questionnaire-forms
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:noNamespaceSchemaLocation='jaxb/super_binding/XSDforWizard.xsd'>
    <questionnaire-form form-id="prevTestForm">
        <form-name>testPreviousButton</form-name>
        <pages>
            <page page-number="1" page-id="formPage1">
                <groups-of-questions>
                    <group group-id="page1Group1">
                        <group-name>Topic 1 of First Page</group-name>
                        <questions>
                            <question answer-required="false" question-id="pageOneGroupOne">
                                <question-title>Question one</question-title>
                                <question-type>TEXT</question-type>
                                <help-text>Type yes if it's topic one of first page?</help-text>
                                <dependent-questions>
                                    <dependent-question/>
                                </dependent-questions>
                                <options>
                                    <option></option>
                                </options>
                                <range/>
                                <grid>
                                    <columns>
                                        <column></column>
                                    </columns>
                                    <rows>
                                        <row></row>
                                    </rows>
                                </grid>
                                <default-answers>
                                    <default-answer>no</default-answer>
                                </default-answers>
                            </question>

                        </questions>
                    </group>
                    <group group-id="page1Group2">
                        <group-name>Topic 2 of First Page</group-name>
                        <questions>
                            <question answer-required="false" question-id="pageOneGroupTwo">
                                <question-title>Question two</question-title>
                                <question-type>MULTIPLECHOICE</question-type>
                                <help-text>Question two</help-text>
                                <dependent-questions>
                                    <dependent-question/>
                                </dependent-questions>
                                <options>
                                    <option>Male</option>
                                    <option>Female</option>
                                </options>
                                <range/>
                                <grid>
                                    <columns>
                                        <column></column>
                                    </columns>
                                    <rows>
                                        <row></row>
                                    </rows>
                                </grid>
                                <default-answers>
                                    <default-answer></default-answer>
                                </default-answers>
                            </question>
                        </questions>
                    </group>
                    <group group-id="page1Group3">
                        <group-name>Topic 3 of First Page</group-name>
                        <questions>
                            <question answer-required="false" question-id="pageOneGroupThree">
                                <question-title>Question three</question-title>
                                <question-type>TEXT</question-type>
                                <help-text>help</help-text>
                                <dependent-questions>
                                    <dependent-question/>
                                </dependent-questions>
                                <options>
                                    <option></option>
                                </options>
                                <range/>
                                <grid>
                                    <columns>
                                        <column></column>
                                    </columns>
                                    <rows>
                                        <row></row>
                                    </rows>
                                </grid>
                                <default-answers>
                                    <default-answer>NoName</default-answer>
                                </default-answers>
                            </question>

                        </questions>
                    </group>
                </groups-of-questions>
            </page>
            <page page-number="2" page-id="formPage2">
                <groups-of-questions>
                    <group group-id="page2Group1">
                        <group-name>Topic 1 of Second Page</group-name>
                        <questions>
                            <question answer-required="false" question-id="pageTwoGroupOne">
                                <question-title>Question four</question-title>
                                <question-type>MULTIPLECHOICE</question-type>
                                <help-text>Male or Female</help-text>
                                <dependent-questions>
                                    <dependent-question/>
                                </dependent-questions>
                                <options>
                                    <option>Male</option>
                                    <option>Female</option>
                                </options>
                                <range/>
                                <grid>
                                    <columns>
                                        <column></column>
                                    </columns>
                                    <rows>
                                        <row></row>
                                    </rows>
                                </grid>
                                <default-answers>
                                    <default-answer></default-answer>
                                </default-answers>
                            </question>
                        </questions>
                    </group>
                    <group group-id="page2Group2">
                        <group-name>Topic 2 of Second Page</group-name>
                        <questions>
                            <question answer-required="false" question-id="pageTwoGroupTwo">
                                <question-title>Question five</question-title>
                                <question-type>PARAGRAPHTEXT</question-type>
                                <help-text>Male or Female</help-text>
                                <dependent-questions>
                                    <dependent-question/>
                                </dependent-questions>
                                <options>
                                    <option></option>

                                </options>
                                <range/>
                                <grid>
                                    <columns>
                                        <column></column>
                                    </columns>
                                    <rows>
                                        <row></row>
                                    </rows>
                                </grid>
                                <default-answers>
                                    <default-answer></default-answer>
                                </default-answers>
                            </question>
                        </questions>
                    </group>
                </groups-of-questions>

            </page>
        </pages>
    </questionnaire-form>
</questionnaire-forms>

=== engagepoint/labs-questionnaire-wizard/wizard-ejb/src/main/resources/testparser.xml
<?xml version="1.0" encoding="UTF-8"?>
<questionnaire-forms
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:noNamespaceSchemaLocation='jaxb/super_binding/XSDforWizard.xsd'>
    <questionnaire-form form-id="testController">
        <form-name>TestController</form-name>
        <pages>
            <page page-number="1" page-id="formPage1">
                <groups-of-questions>
                    <group group-id="page1Group1">
                        <group-name>Topic 1 of First Page</group-name>
                        <questions>
                            <question answer-required="false" question-id="pageOneGroupOne">
                                <question-title>Question one</question-title>
                                <question-type>TEXT</question-type>
                                <help-text>Type yes if it's topic one of first page?</help-text>
                                <dependent-questions>
                                    <dependent-question/>
                                </dependent-questions>
                                <options>
                                    <option></option>
                                </options>
                                <range/>
                                <grid>
                                    <columns>
                                        <column></column>
                                    </columns>
                                    <rows>
                                        <row></row>
                                    </rows>
                                </grid>
                                <default-answers>
                                    <default-answer>Default answer</default-answer>
                                </default-answers>
                            </question>
                       </questions>
                    </group>
            </groups-of-questions>
            </page>
        </pages>
    </questionnaire-form>
</questionnaire-forms>

=== engagepoint/labs-questionnaire-wizard/wizard-ejb/src/main/resources/XMLforWizard.xml
<?xml version="1.0" encoding="UTF-8"?>
<questionnaire-forms
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='jaxb/super_binding/XSDforWizard.xsd'>
    <questionnaire-form form-id="bcdmlpq1">
        <form-name>Simple Form Template 1</form-name>
        <pages>
            <page page-number="1" page-id="dcvxd">
                <groups-of-questions>
                    <group group-id="bcugyrfn">
                        <group-name>test group name</group-name>
                        <questions>
                            <question answer-required="true" question-id="1">
                                <question-title>Error Q</question-title>
                                <question-type>TEXT</question-type>
                                <help-text></help-text>
                                <dependent-questions>
                                    <dependent-question required-answer="lalalal" question-id="3"/>
                                </dependent-questions>
                                <options>
                                    <option></option>
                                </options>
                                <range/>
                                <grid>
                                    <columns>
                                        <column></column>
                                    </columns>
                                    <rows>
                                        <row></row>
                                    </rows>
                                </grid>
                            </question>
                            <question>
                                <question-title>CheckBox Q</question-title>
                                <question-type>CHECKBOX</question-type>
                                <help-text>help</help-text>
                                <dependent-questions>
                                    <dependent-question/>
                                </dependent-questions>
                                <options>
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                </options>
                                <range/>
                                <grid>
                                    <columns>
                                        <column></column>
                                    </columns>
                                    <rows>
                                        <row></row>
                                    </rows>
                                </grid>
                            </question>
                        </questions>
                    </group>
                </groups-of-questions>
            </page>
        </pages>
    </questionnaire-form>
</questionnaire-forms>
